### ISSUE TITLE
[EX6100v2] Timeout while waiting for TFTP_UL_REQ

### ISSUE THREAD

**Issue by orowith2os** [jclehner/nmrpflash#119]
I've bricked my netgear repeater in the process of setting it up to be a system that I'm comfortable using, and accidentally removed the Luci GUI (and, now, can't even SSH in).

I'm flashing the router using the following command: `sudo ./nmrpflash -i enp34s0 -f ~/Downloads/openwrt-22.03.2-ipq40xx-generic-netgear_ex6100v2-squashfs-factory.img -vvv`

Here's what I get near the end:
```
<< DATA(25729)
>> ACK(25729)
OK (13172865 b)
Waiting for remote to respond.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Received configuration request from 38:94:ed:2e:6b:b9.
Sending configuration: 10.0.0.1/24.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 38:94:ed:2e:6b:b9.
Sending configuration: 10.0.0.1/24.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 38:94:ed:2e:6b:b9.
Sending configuration: 10.0.0.1/24.
Timeout while waiting for TFTP_UL_REQ.
```

If there are any additional details I can provide, please do ask for them.

I've also tried using the stock Neatgear firmware.

**Comment by jclehner** [comment]
Have you tried OpenWRT's [failsafe](https://openwrt.org/docs/guide-user/troubleshooting/failsafe_and_factory_reset#failsafe_mode) mode? 

Also, when you first flashed OpenWRT, did you use `nmrpflash`, or did you go via the stock web interface?

The router is rejecting the firmware image, which could be due to a version mismatch. I've only seen this with `chk` images so far, but your device uses the `dni` format.

Attached you'll find an image that matches the data of `openwrt-22.03.2-ipq40xx-generic-netgear_ex6100v2-squashfs-factory.img`, but uses a different version internally. Try flashing that, and report back (remember to extract the `.zip` first):

[openwrt-22.03.2-ipq40xx-generic-netgear_ex6100v2-squashfs-factory_V1.0.1.109.img.zip](https://github.com/jclehner/nmrpflash/files/10211940/openwrt-22.03.2-ipq40xx-generic-netgear_ex6100v2-squashfs-factory_V1.0.1.109.img.zip)

**Comment by orowith2os** [comment]
Small update, I've finally got it working, through a mix of clicking the reset button and trying to reflash.

No clue what happened, but if I ever have to do this again, I'll be sure to come back here~

Gonna close the issue until next time.
