### ISSUE TITLE
R6120 will not restart

### ISSUE THREAD

**Issue by JTD6120** [jclehner/nmrpflash#48]
I have a Netgear R6120. I did an update with the router login page from Netgear, and it crashed. I have tried to tftp directions with no luck and found your fix and followed the steps line by line. It does complete the flash all the way to "reboot your device now" with the power led flashing. When i reboot, i get 1 of 2 responses:
1) if I just turn it off with the power button and turn it on,  I get the ethernet led quickly flashes on and off, and then the power led comes on for 20 seconds, then the ethernet quickly flashes on and off, and then the power led comes on for 20 seconds and it continues this routine for 6 cycles and then the power light goes out  and i get nothing again.
2) if I hold the factory reset button while turning it on, i get back to the power led alternating with the ethernet led

```
C:\Users\Jeff\Desktop\nmrpflash>nmrpflash -i net6 -f openwrt-19.07.3-ramips-mt76x8-netgear_r6120-squashfs-factory.img -A192.168.1.2 -a 192.168.1.1
Advertising NMRP server on net2 ... |
Received configuration request from 78:d2:94:70:7c:ae.
Sending configuration: 192.168.1.1/24.
Received upload request without filename.
Uploading openwrt-19.07.3-ramips-mt76x8-netgear_r6120-squashfs-factory.img ... OK
Waiting for remote to respond.
Received keep-alive request (3).
Remote finished. Closing connection.
Reboot your device now.
```

when I try to ping it:

```
C:\Users\Jeff\Desktop\nmrpflash>ping 192.168.1.1

Pinging 192.168.1.1 with 32 bytes of data:
Reply from 192.168.1.2: Destination host unreachable.
Reply from 192.168.1.2: Destination host unreachable.
Reply from 192.168.1.2: Destination host unreachable.
Reply from 192.168.1.2: Destination host unreachable.

Ping statistics for 192.168.1.1:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss)
```

 Any suggestions or is this router dead?

**Comment by jclehner** [comment]
I'm assuming you've tried flashing the latest stock firmware as well?

**Comment by jclehner** [comment]
Hi. The "without filename" bit itself is nothing to worry about. It's just that some devices include a file name in the request, and others don't. 

> I did an update with the router login page from Netgear, and it crashed.

Do you mean that the device stopped working while the update was in progress? If so, this might have trashed some factory partitions neccessary for the correct operation of the firmware.

> [...] or is it hopeless?

The bootloader at least appears to be intact, otherwise `nmrpflash` wouldn't work. Have you tried [failsafe mode](https://openwrt.org/docs/guide-user/troubleshooting/failsafe_and_factory_reset#entering_failsafe_mode)?

If that still doesn't work, a [serial connection](https://openwrt.org/toh/netgear/netgear_r6120#serial) would aid greatly in diagnosing this issue, but this will require basic soldering skills, and the right equipment.
