### ISSUE TITLE
Story about my R6220: Request adding a tip to README.md

### ISSUE THREAD

**Issue by recolic** [jclehner/nmrpflash#75]
# Request to update README

Tip: If `nmrpflash before power-on` is always not working, try `nmrpflash after power-on`. 

# Why this request

I'm rescuing my Netgear R6220. I tried to exactly follow the guide: 

1. run `nmrpflash -i enp5s0 -f R6220_V1.1.0.106_1.0.1.img`, it says `Waiting for physical connection.`

2. power on my router R6220

3. nmrpflash fails with `bind: Cannot assign requested address`. 

I tried 5 times, and I tried both your pre-built binary and building from source. Neither of them works. 

I also tried to use `-A 192.168.1.2 -a 192.168.1.1`, it's also not working. 

============

Now I'm tired. I power on my router first, and then run `nmrpflash`. Magically, it hangs on `uploading R6220_xxx.img` and it seems to be working. (Then it fails with `sendto: Network is unreachable`)

Now I try `nmrpflash -i enp5s0 -f R6220_V1.1.0.106_1.0.1.img` again, it says `Waiting for physical connection` but the router is already powered on. 

So I powered-off my router, and powered-on it again. Now some magic happens: everything is working, and nmrpflash finally succeeded!

```
Waiting for physical connection.
Advertising NMRP server on enp5s0 ... \
Received configuration request from 50:6a:03:e9:dc:b0.
Sending configuration: 10.164.183.252/24.
Received upload request without filename.
Uploading R6220_V1.1.0.106_1.0.1.img ... OK
Waiting for remote to respond.
Received keep-alive request (51).  
Remote finished. Closing connection.
Reboot your device now.
```

============

I hope that my story would help you. If `nmrpflash before power-on` is always not working, try `nmrpflash after power-on`.

**Comment by jclehner** [comment]
Hi. I've finally traced this issue down to the following sequence of events:

1. `nmrpflash`  adds the IP address to the network interface
2. [NetworkManager](https://developer.gnome.org/NetworkManager/stable/NetworkManager.html) fails to get an IP address via DHCP, and re-creates the interface, thus removing all IP addresses.
3. `nmrpflash` tries to use an IP address, that has since been removed.

I've added a workaround that temporarily disables NetworkManager on the interface used by `nmrpflash`, which should avoid such race conditions in the future.

Before that, I could reliably trigger the `bind` error using the following steps:

1. Connect the router, and set the interface to auto-configure using NetworkManager.
2. Once you've received the first error message, that auto-configuring has failed, turn off the router.
3. Now run `nmrpflash`, and turn on the router as soon as you see the `Waiting for physical connection` message.

Please verify whether the issue has been fixed on your device as well, and report back!

**Comment by recolic** [comment]
Hi, 

I'm sorry that I can not do the verification, because I have already sold my router to others... 
it's very likely that you are correct, because I have NetworkManager enabled while performing the test. But my device has gone, and unable to confirm this...

**Comment by jclehner** [comment]
No problem! I'll close this for now though.
